version: '3.0'
services:

  ### ZOOKEEPER ###

  zoo-1:
    image: "zookeeper:latest"
    container_name: "zoo_1"
    environment:
       ZOO_MY_ID: 1
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg


  zoo-2:
    image: "zookeeper:latest"
    container_name: "zoo_2"
    environment:
       ZOO_MY_ID: 2
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg


  zoo-3:
    image: "zookeeper:latest"
    container_name: "zoo_3"
    environment:
      ZOO_MY_ID: 3
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg



  ### MESOS MASTER ###

  mesos-master-1:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_1"
    env_file:
      - ./mesos-master-env
    environment:
      - MESOS_HOSTNAME=mesos-master-1
    volumes:
      - /tmp/log/mesos_1:/var/log/mesos
      - /tmp/tmp/mesos_1:/var/tmp/mesos


  mesos-master-2:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_2"
    env_file:
      - ./mesos-master-env
    environment:
      - MESOS_HOSTNAME=mesos-master-2
    volumes:
      - /tmp/log/mesos_2:/var/log/mesos
      - /tmp/tmp/mesos_2:/var/tmp/mesos


  mesos-master-3:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_3"
    env_file:
      - ./mesos-master-env
    environment:
      - MESOS_HOSTNAME=mesos-master-3
    volumes:
      - /tmp/log/mesos_3:/var/log/mesos
      - /tmp/tmp/mesos_3:/var/tmp/mesos
