version: '3.0'
services:

  zoo1:
    image: "zookeeper:latest"
    container_name: "zoo_1"
    environment: 
       ZOO_MY_ID: 1
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg
    ports: 
      - "2181:2181"


  zoo2:
    image: "zookeeper:latest"
    container_name: "zoo_2"
    environment:
       ZOO_MY_ID: 2
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg
    ports:
      - "2182:2181"


  zoo3:
    image: "zookeeper:latest"
    container_name: "zoo_3"
    environment:
      ZOO_MY_ID: 3
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg
    ports:
      - "2183:2181"





  mesos-master-1:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_1"
    env_file:
      - ./mesos-master-env
    volumes:
      - ./log/mesos_1:/var/log/mesos
      - ./tmp/mesos_1:/var/tmp/mesos
    ports:
      - "5050:5050"
     

  mesos-master-2:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_2"
    env_file:
      - ./mesos-master-env
    volumes:
      - ./log/mesos_2:/var/log/mesos
      - ./tmp/mesos_2:/var/tmp/mesos
    ports:
      - "5051:5050"


  mesos-master-3:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_3"
    env_file:
      - ./mesos-master-env
    volumes:
      - ./log/mesos_3:/var/log/mesos
      - ./tmp/mesos_3:/var/tmp/mesos
    ports:
      - "5052:5050"





  thermos1:
    image: "pkleindienst/aurora-executor:latest"
    container_name: "aurora-executor_1"
    env_file:
      - ./executor-env
    volumes:
      - ./tmp/mesos-slave:/var/tmp/mesos
      - ./log/mesos-slave:/var/log/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
    


  aurora1:
    image: "pkleindienst/aurora-scheduler:latest"
    container_name: "aurora-scheduler-1"
    env_file:
      - ./scheduler1-env
    ports:
      - "8081:8088"

  aurora2:
    image: "pkleindienst/aurora-scheduler:latest"
    container_name: "aurora-scheduler-2"
    env_file:
      - ./scheduler2-env
    ports:
      - "8082:8088"

  aurora3:
    image: "pkleindienst/aurora-scheduler:latest"
    container_name: "aurora-scheduler-3"
    env_file:
      - ./scheduler3-env
    ports:
      - "8083:8088"


  aurora-cli:
    image: "pkleindienst/aurora-cli"
    container_name: "aurora_cli"
    volumes:
      - ./clusters.json:/var/aurora/clusters.json
      - ./nginx-docker.aurora:/nginx-docker.aurora
    entrypoint: sleep 1000000


