version: '3.0'
services:

  ### ZOOKEEPER ###

  zoo-1:
    image: "zookeeper:latest"
    container_name: "zoo_1"
    environment:
       ZOO_MY_ID: 1
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg


  zoo-2:
    image: "zookeeper:latest"
    container_name: "zoo_2"
    environment:
       ZOO_MY_ID: 2
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg


  zoo-3:
    image: "zookeeper:latest"
    container_name: "zoo_3"
    environment:
      ZOO_MY_ID: 3
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg



  ### MESOS MASTER ###

  mesos-master-1:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_1"
    env_file:
      - ./mesos-master-env
    environment:
      - MESOS_HOSTNAME=mesos-master-1
    volumes:
      - /tmp/mesos_log/master_1:/var/log/mesos
      - /tmp/mesos_tmp/master_1:/var/tmp/mesos


  mesos-master-2:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_2"
    env_file:
      - ./mesos-master-env
    environment:
      - MESOS_HOSTNAME=mesos-master-2
    volumes:
      - /tmp/mesos_log/master_2:/var/log/mesos
      - /tmp/mesos_tmp/master_2:/var/tmp/mesos


  mesos-master-3:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_3"
    env_file:
      - ./mesos-master-env
    environment:
      - MESOS_HOSTNAME=mesos-master-3
    volumes:
      - /tmp/mesos_log/master_3:/var/log/mesos
      - /tmp/mesos_tmp/master_3:/var/tmp/mesos


  ### MESOS AGENT ###

  mesos-agent-1:
    image: "mesosphere/mesos-slave:1.1.1"
    container_name: "mesos_agent_1"
    env_file:
      - ./marathon/mesos-agent-env
    volumes:
      - /tmp/mesos_tmp/agent_1:/var/tmp/mesos
      - /tmp/mesos_log/agent_1:/var/log/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
    environment:
      - MESOS_HOSTNAME=mesos-agent-1


  mesos-agent-2:
    image: "mesosphere/mesos-slave:1.1.1"
    container_name: "mesos_agent_2"
    env_file:
      - ./marathon/mesos-agent-env
    volumes:
      - /tmp/mesos_tmp/agent_2:/var/tmp/mesos
      - /tmp/mesos_log/agent_2:/var/log/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
    environment:
      - MESOS_HOSTNAME=mesos-agent-2

  mesos-agent-3:
    image: "pkleindienst/aurora-worker:latest"
    container_name: "mesos_worker_3"
    env_file:
      - ./marathon/mesos-agent-env
    volumes:
      - /tmp/mesos_tmp/agent_3:/var/tmp/mesos
      - /tmp/mesos_log/agent_3:/var/log/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
    environment:
      - MESOS_HOSTNAME=mesos-agent-3
