version: '3.0'
services:

  ### ZOOKEEPER ###

  zoo-1:
    image: "zookeeper:latest"
    container_name: "zoo_1"
    environment:
       ZOO_MY_ID: 1
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg


  zoo-2:
    image: "zookeeper:latest"
    container_name: "zoo_2"
    environment:
       ZOO_MY_ID: 2
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg


  zoo-3:
    image: "zookeeper:latest"
    container_name: "zoo_3"
    environment:
      ZOO_MY_ID: 3
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg



  ### MESOS MASTER ###

  mesos-master-1:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_1"
    env_file:
      - ./mesos-master-env
    environment:
      - MESOS_HOSTNAME=mesos-master-1
    volumes:
      - /tmp/log/mesos_1:/var/log/mesos
      - /tmp/tmp/mesos_1:/var/tmp/mesos


  mesos-master-2:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_2"
    env_file:
      - ./mesos-master-env
    environment:
      - MESOS_HOSTNAME=mesos-master-2
    volumes:
      - /tmp/log/mesos_2:/var/log/mesos
      - /tmp/tmp/mesos_2:/var/tmp/mesos


  mesos-master-3:
    image: "mesosphere/mesos-master:1.1.1"
    container_name: "mesos_master_3"
    env_file:
      - ./mesos-master-env
    environment:
      - MESOS_HOSTNAME=mesos-master-3
    volumes:
      - /tmp/log/mesos_3:/var/log/mesos
      - /tmp/tmp/mesos_3:/var/tmp/mesos



  ### MESOS AGENT ###

  mesos-worker-1:
    image: "pkleindienst/aurora-worker:latest"
    container_name: "mesos_worker_1"
    env_file:
      - ./executor-env
    volumes:
      - /tmp/tmp/mesos-slave1:/var/tmp/mesos
      - /tmp/log/mesos-slave1:/var/log/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
    environment:
      - MESOS_HOSTNAME=mesos-worker-1


  mesos-worker-2:
    image: "pkleindienst/aurora-worker:latest"
    container_name: "mesos_worker_2"
    env_file:
      - ./executor-env
    volumes:
      - /tmp/tmp/mesos-slave2:/var/tmp/mesos
      - /tmp/log/mesos-slave2:/var/log/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
    environment:
      - MESOS_HOSTNAME=mesos-worker-2

  mesos-worker-3:
    image: "pkleindienst/aurora-worker:latest"
    container_name: "mesos_worker_3"
    env_file:
      - ./executor-env
    volumes:
      - /tmp/tmp/mesos-slave3:/var/tmp/mesos
      - /tmp/log/mesos-slave3:/var/log/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
    environment:
      - MESOS_HOSTNAME=mesos-worker-3



  ### AURORA ###

  aurora-1:
    image: "pkleindienst/aurora-scheduler:latest"
    container_name: "aurora-scheduler-1"
    env_file:
      - ./aurora-scheduler-env
    environment:
      - HOSTNAME=aurora1

  aurora-2:
    image: "pkleindienst/aurora-scheduler:latest"
    container_name: "aurora-scheduler-2"
    env_file:
      - ./aurora-scheduler-env
    environment:
      - HOSTNAME=aurora2

  aurora-3:
    image: "pkleindienst/aurora-scheduler:latest"
    container_name: "aurora-scheduler-3"
    env_file:
      - ./aurora-scheduler-env
    environment:
      - HOSTNAME=aurora3


  ### MARATHON ###

  marathon-1:
      image: "mesosphere/marathon:v1.4.2"
      container_name: "marathon-scheduler-1"
      env_file:
        - ./marathon-env

  marathon-2:
      image: "mesosphere/marathon:v1.4.2"
      container_name: "marathon-scheduler-2"
      env_file:
        - ./marathon-env

  marathon-3:
      image: "mesosphere/marathon:v1.4.2"
      container_name: "marathon-scheduler-3"
      env_file:
        - ./marathon-env
