version: '3.0'
services:


  ### MESOS AGENT ###

  mesos-agent-1:
    image: "pkleindienst/aurora-worker:latest"
    container_name: "mesos_agent_1"
    env_file:
      - ./aurora/mesos-worker-env
    volumes:
      - /tmp/mesos_tmp/agent_1:/var/tmp/mesos
      - /tmp/mesos_log/agent_1:/var/log/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
    environment:
      - MESOS_HOSTNAME=mesos-agent-1


  mesos-agent-2:
    image: "pkleindienst/aurora-worker:latest"
    container_name: "mesos_agent_2"
    env_file:
      - ./aurora/mesos-worker-env
    volumes:
      - /tmp/mesos_tmp/agent_2:/var/tmp/mesos
      - /tmp/mesos_log/agent_2:/var/log/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
    environment:
      - MESOS_HOSTNAME=mesos-agent-2
      mesos-agent-3:

    image: "pkleindienst/aurora-worker:latest"
    container_name: "mesos_agent_3"
    env_file:
      - ./aurora/mesos-worker-env
    volumes:
      - /tmp/mesos_tmp/agent_3:/var/tmp/mesos
      - /tmp/mesos_log/agent_3:/var/log/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
    environment:
      - MESOS_HOSTNAME=mesos-agent-3



  ### AURORA ###

  aurora-1:
    image: "pkleindienst/aurora-scheduler:latest"
    container_name: "aurora_scheduler_1"
    env_file:
      - ./aurora/aurora-scheduler-env
    environment:
      - HOSTNAME=aurora-1

  aurora-2:
    image: "pkleindienst/aurora-scheduler:latest"
    container_name: "aurora_scheduler_2"
    env_file:
      - ./aurora/aurora-scheduler-env
    environment:
      - HOSTNAME=aurora-2

  aurora-3:
    image: "pkleindienst/aurora-scheduler:latest"
    container_name: "aurora_scheduler_3"
    env_file:
      - ./aurora/aurora-scheduler-env
    environment:
      - HOSTNAME=aurora-3


  ### MARATHON ###

  marathon-1:
    image: "mesosphere/marathon:v1.4.2"
    container_name: "marathon_scheduler_1"
    env_file:
      - ./marathon/marathon-env

  marathon-2:
    image: "mesosphere/marathon:v1.4.2"
    container_name: "marathon_scheduler_2"
    env_file:
      - ./marathon/marathon-env

  marathon-3:
    image: "mesosphere/marathon:v1.4.2"
    container_name: "marathon_scheduler_3"
    env_file:
      - ./marathon/marathon-env
